require('../database/connect')
const express= require("express")
const app = express()
const cors = require("cors")
app.use(express.json())
app.use(cors())
const path = require("path")
const staticDir = path.join(__dirname, "../images")
app.use(express.static(staticDir))
app.use(express.urlencoded({extended:true}))
const movieRoutes=require("../routes/movie.routes")
const theaterRouters=require('../routes/theater.routes')
const ticketRouters=require('../routes/ticket.routes')
const userRouters=require('../routes/user.routes')
app.use("/movie",movieRoutes)
app.use("/theater",theaterRouters)
app.use("/ticket",ticketRouters)
app.use("/user",userRouters)
module.exports = app
