require('../database/connect')
const express= require("express")
const app = express()
app.use(express.json())
app.use(express.urlencoded({extended:true}))
const movieRoutes=require("../routes/movie.routes")
const theaterRouters=require('../routes/theater.routes')
const ticketRouters=require('../routes/ticket.routes')
app.use("/movie",movieRoutes)
app.use("/theater",theaterRouters)
app.use("/ticket",ticketRouters)
module.exports = app
